### ISSUE TITLE
Static website for the documentation

### ISSUE THREAD

**Issue by ammarasmro** [remon/pythonCodes#13]
Hello everyone! I just read about this project on the Udacity forums and I'm very excited to start contributing to it.

I have an idea to further push this project by presenting it in a lightweight static website. I have used HUGO framework before and it would make it easier to attract more help. What do you think? @remon

**Comment by remon** [comment]
I am working on it 

but if you can do it , so why not

**Comment by ammarasmro** [comment]
Awesome, I'll try to make a prototype. Do you have any preference for a framework or a theme?

I found this theme and I think it has many functionalities that might be useful for us [Hugo Learn Theme](https://themes.gohugo.io/theme/hugo-theme-learn/en)

**Comment by ammore5** [comment]
If I've understood you correctly, I suggest you use Google Docs. Like what he did in the following video:
[google docs](https://www.youtube.com/watch?v=GcvvbdKEchk&feature=youtu.be)

**Comment by ammarasmro** [comment]
Yes that is one way to do it. There are many ways to make a documentation but I prefer static web frameworks as they allow me to use Markdown to write posts with very good support for different formatting. This way we can also include demos and widgets within the website, things that we can't do in a Google Doc. 

Another benefit of the theme I suggested is that it structures content in an educative format so that one can browse the content as chapters sorted by difficulty.
